services:
  app:
    user: "0"
    environment:
      PHP_OPCACHE_ENABLE: "false"
    volumes:
      - type: volume
        source: composer_cache
        # composer config --global cache-dir
        target: /root/.composer/cache
      - type: bind
        source: ./app
        target: /app
    working_dir: /app

volumes:
  composer_cache:
    driver: local
    name: global_composer_cache
