services:
  app:
    user: "0"
    environment:
      #Symfony
      APP_ENV: "dev"
      APP_DEBUG: "0"
      APP_SECRET: "00000000000000000000000000000000"
      VERSION: "0.1.2"
      PHP_OPCACHE_ENABLE: "false"

      # Logs
      CADDY_LOG_OUTPUT: "file /app/var/log/caddy.log"
      CADDY_LOG_LEVEL: "INFO"
      FPM_ACCESS_LOG: "/app/var/log/php-fpm.access.log"
      FPM_ERROR_LOG: "/app/var/log/php-fpm.error.log"
      FPM_LOG_LEVEL: "notice"
      PHP_ERROR_LOG: "/app/var/log/php.error.log"
      PHP_LOG_LEVEL: "E_ALL"
      XDEBUG_OUTPUT_DIR: "/app/var/log"
    volumes:
      - type: volume
        source: composer_cache
        # composer config --global cache-dir
        target: /root/.composer/cache
      - type: bind
        source: ./app
        target: /app
    working_dir: /app

volumes:
  composer_cache:
    driver: local
    name: global_composer_cache
