services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/archi-tektur/invoicer:app-${VERSION:-0.1.1}
    environment:
      HTTP_API_TESTS_ENTRYPOINT: http://app:8080
