kernel:
    resource: ../../src/Shared/Infrastructure/Symfony/Kernel.php
    type: annotation

health_check:
  resource: ../../src/Shared/Infrastructure/Symfony/Controller/
  type: annotation

user:
  resource: ../../src/User/Infrastructure/Symfony/Controller/
  type: annotation
