doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Shared:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Entity/'
        prefix: 'App\Shared'
        alias: Shared
      User:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/User/Infrastructure/Doctrine/Entity/'
        prefix: 'App\User'
        alias: User
